# Generated by Django 4.0.5 on 2022-06-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='mainapp/food_images/placeholder.jiff', height_field=232, upload_to='mainapp/food_images/', width_field=232),
        ),
    ]
